import {
  Race,
  Background,
  Class,
  ArmorTypes,
  WeaponTypes,
  AbilityScore,
  Alignment,
  Skill,
  Size,
  Features,
} from '@prisma/client';

const featureData: Features[] = [
  {
    id: 1,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Rage',
    description:
      'In battle, you fight with primal ferocity. On your turn, you can enter a rage as a bonus action.',
    level: 1,
    classId: 1,
    subClassId: null,
  },
  {
    id: 2,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Unarmored Defense',
    description:
      'While you are not wearing any armor, your Armor Class equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit.',
    level: 1,
    classId: 1,
    subClassId: null,
  },
  {
    id: 3,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Reckless Attack',
    description:
      'Starting at 2nd level, you can throw aside all concern for defense to attack with fierce desperation. When you make your first attack on your turn, you can decide to attack recklessly.',
    level: 2,
    classId: 1,
    subClassId: null,
  },
  {
    id: 4,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Danger Sense',
    description:
      'At 2nd level, you gain an uncanny sense of when things nearby aren’t as they should be, giving you an edge when you dodge away from danger.',
    level: 2,
    classId: 1,
    subClassId: null,
  },
  {
    id: 5,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Primal Path',
    description:
      'At 3rd level, you choose a path that shapes the nature of your rage. Choose the Path of the Berserker or the Path of the Totem Warrior, both detailed at the end of the class description.',
    level: 3,
    classId: 1,
    subClassId: null,
  },
  {
    id: 6,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Extra Attack',
    description:
      'Beginning at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.',
    level: 5,
    classId: 1,
    subClassId: null,
  },
  {
    id: 7,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Fast Movement',
    description:
      'Starting at 5th level, your speed increases by 10 feet while you aren’t wearing heavy armor.',
    level: 5,
    classId: 1,
    subClassId: null,
  },
  {
    id: 8,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Feral Instinct',
    description:
      'By 7th level, your instincts are so honed that you have advantage on initiative rolls.',
    level: 7,
    classId: 1,
    subClassId: null,
  },
  {
    id: 9,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Brutal Critical',
    description:
      'Beginning at 9th level, you can roll one additional weapon damage die when determining the extra damage for a critical hit with a melee attack.',
    level: 9,
    classId: 1,
    subClassId: null,
  },
  {
    id: 10,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Relentless Rage',
    description:
      'Starting at 11th level, your rage can keep you fighting despite grievous wounds. If you drop to 0 hit points while you’re raging and don’t die outright, you can make a DC 10 Constitution saving throw.',
    level: 11,
    classId: 1,
    subClassId: null,
  },
  {
    id: 11,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Persistent Rage',
    description:
      'Beginning at 15th level, your rage is so fierce that it ends early only if you fall unconscious or if you choose to end it.',
    level: 15,
    classId: 1,
    subClassId: null,
  },
  {
    id: 12,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Indomitable Might',
    description:
      'Beginning at 18th level, if your total for a Strength check is less than your Strength score, you can use that score in place of the total.',
    level: 18,
    classId: 1,
    subClassId: null,
  },
  {
    id: 13,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Primal Champion',
    description:
      'At 20th level, you embody the power of the wilds. Your Strength and Constitution scores increase by 4. Your maximum for those scores is now 24.',
    level: 20,
    classId: 1,
    subClassId: null,
  },
  {
    id: 14,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Spellcasting',
    description:
      'You have learned to untangle and reshape the fabric of reality in harmony with your wishes and music.',
    level: 1,
    classId: 2,
    subClassId: null,
  },
  {
    id: 15,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Bardic Inspiration',
    description:
      'You can inspire others through stirring words or music. To do so, you use a bonus action on your turn to choose one creature other than yourself within 60 feet of you who can hear you.',
    level: 1,
    classId: 2,
    subClassId: null,
  },
  {
    id: 16,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Jack of All Trades',
    description:
      'Starting at 2nd level, you can add half your proficiency bonus, rounded down, to any ability check you make that doesn’t already include your proficiency bonus.',
    level: 2,
    classId: 2,
    subClassId: null,
  },
  {
    id: 17,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Song of Rest',
    description:
      'Beginning at 2nd level, you can use soothing music or oration to help revitalize your wounded allies during a short rest.',
    level: 2,
    classId: 2,
    subClassId: null,
  },
  {
    id: 18,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Expertise',
    description:
      'At 3rd level, choose two of your skill proficiencies. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies.',
    level: 3,
    classId: 2,
    subClassId: null,
  },
  {
    id: 19,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Font of Inspiration',
    description:
      'Beginning when you reach 5th level, you regain all of your expended uses of Bardic Inspiration when you finish a short or long rest.',
    level: 5,
    classId: 2,
    subClassId: null,
  },
  {
    id: 20,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Countercharm',
    description:
      'At 6th level, you gain the ability to use musical notes or words of power to disrupt mind-influencing effects',
    level: 6,
    classId: 2,
    subClassId: null,
  },
  {
    id: 21,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Magical Secrets',
    description:
      'By 10th level, you have plundered magical knowledge from a wide spectrum of disciplines. Choose two spells from any classes, including this one.',
    level: 10,
    classId: 2,
    subClassId: null,
  },
  {
    id: 22,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Superior Inspiration',
    description:
      'At 20th level, when you roll initiative and have no uses of Bardic Inspiration left, you regain one use.',
    level: 20,
    classId: 2,
    subClassId: null,
  },
  {
    id: 23,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Spellcasting',
    description: 'As a conduit for divine power, you can cast Cleric Spells.',
    level: 1,
    classId: 3,
    subClassId: null,
  },
  {
    id: 24,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Divine Domain',
    description:
      'Choose one domain related to your deity: Knowledge, Life, Light, Nature, Tempest, Trickery, or War.',
    level: 1,
    classId: 3,
    subClassId: null,
  },
  {
    id: 25,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Channel Divinity',
    description:
      'At 2nd level, you gain the ability to channel divine energy directly from your deity, using that energy to fuel magical effects.',
    level: 2,
    classId: 3,
    subClassId: null,
  },
  {
    id: 26,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Destroy Undead',
    description:
      'Starting at 5th level, when an undead fails its saving throw against your Turn Undead feature, the creature is instantly destroyed if its challenge rating is at or below a certain threshold.',
    level: 5,
    classId: 3,
    subClassId: null,
  },
  {
    id: 27,
    contentPackId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: 'Divine Intervention',
    description:
      'Beginning at 10th level, you can call on your deity to intervene on your behalf when your need is great.',
    level: 10,
    classId: 3,
    subClassId: null,
  },
];

export default featureData;
