export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "./globals.css";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-blue-950 w-full min-h-screen text-white font-mono ">
        {children}
      </body>
    </html>
  );
}
